export const config = {
    videosBaseUrl: 'http://office.radioairplay.fm',
    jwtToken: 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImlVVGo4RmV2NVpoNm5UeFR3eWR5N2ciLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE2NDI1MjY2ODEsImV4cCI6MTY0MjUzMDI4MSwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5haXJwbGF5Y29udHJvbC5jb20iLCJhdWQiOiJTcG90Q2hlY2tBcGkiLCJjbGllbnRfaWQiOiJTcG90Q2hlY2tBcGlTd2FnZ2VyIiwic3ViIjoiNWU0ZTg2NDItZDgwNS00MWIwLTlhZTEtNjk2M2M3OTU2NjQwIiwiYXV0aF90aW1lIjoxNjQyNTI2Njc4LCJpZHAiOiJsb2NhbCIsIm5hbWUiOiJNaWNoYWVsIFBoYW0iLCJyb2xlIjpbIlNwb3RDaGVja1VzZXIiLCJTcG90Q2hlY2tBZG1pbiIsIklkZW50aXR5U2VydmVyQWRtaW5Sb2xlIl0sInNjb3BlIjpbIlNwb3RDaGVja0FwaSJdLCJhbXIiOlsicHdkIl19.Uw8TAQFOZbCj6JwLeikXAScac1JWDAbRFMvgQEzO9E9LU3DFdKa40IE6wnqfPwgPK9KStKOEoa6LY-7KqNuC_PSxN1_STlBvl1q49Kqhp8aSHsjbZaGyht95ceDdPPuhXdjQue_boS183qzrlMRkZ47FElRwgDArbvTnZZG4_JCv6x3Z_ujEO2qpITtuQNU4Srf0GiMblCWukBlcmBdBd0cZfuyMbIn1anP72L2m7rd5sKCqVeVyMrYr5U5tcfrB6-Drwe76yhWtvg0ofpIoh4g-zSRXaq-T4cE1fj1BUTcQ2d0ra4BSciR_79IXMXNdvT83IsfoIdWDBg3FA32rVg',
    sourcesUrl: process.env.REACT_APP_PROD_SPOTCHECK_API+'/api/Sources',
    companiesUrl: process.env.REACT_APP_PROD_SPOTCHECK_API+'/api/Companies',
    brandsUrl: process.env.REACT_APP_PROD_SPOTCHECK_API+'/api/Brands',
    productsUrl: process.env.REACT_APP_PROD_SPOTCHECK_API+'/api/Products',
    categoriesUrl: process.env.REACT_APP_PROD_SPOTCHECK_API+'/api/SpotCategory',
    subCategoriesUrl: process.env.REACT_APP_PROD_SPOTCHECK_API+'/api/SpotSubCategory',
    tagsUrl: process.env.REACT_APP_PROD_SPOTCHECK_API+'/api/SpotTag',
    spotsUrl: process.env.REACT_APP_PROD_SPOTCHECK_API+'/api/Spots',
    recognitionsUrl: process.env.REACT_APP_PROD_SPOTCHECK_API+'/api/Recognitions/QueryBySourceAndTimestamps',
    proposalsUrl: process.env.REACT_APP_PROD_SPOTCHECK_API+'/api/Proposal/QueryBySourceAndTimestamps',
    saveFingerprintUrl: process.env.REACT_APP_NODE_SERVER+'/saveFingerprintDetails',
    saveAudioFingerprintUrl: process.env.REACT_APP_NODE_SERVER+'/saveAudioFingerprintDetails',
    nodeServerUrl: process.env.REACT_APP_NODE_SERVER, //'http://spt.office.airplaycontrol.com:8000',
    // for now we are using source types as hardcoded as it's not good sending a request on every load but we can do that if asked by management
    // it is copy pasted response from /api/SourceTypes endpoint
    sourceTypes: [
        {
            "sourceTypeUuid": "29621e26-26f2-e911-90cd-00155df10304",
            "name": "Radio",
            "modifiedUtc": "2019-10-19T04:08:53.1766667",
            "details": null
        },
        {
            "sourceTypeUuid": "28621e26-26f2-e911-90cd-00155df10304",
            "name": "Tv",
            "modifiedUtc": "2019-10-19T04:08:48.37",
            "details": null
        }
    ],
    // channels we are recording for right now
    recordingVideoChannels: [
        "20 Mediaset",
        "Canale 5",
        "Cielo",
        "Cine 34",
        "DMAX",
        "Focus",
        "Giallo",
        "Iris",
        "Italia 1",
        "La5",
        "LA7",
        "LA7d",
        "Mediaset Extra",
        "Mediaset Italia 2",
        "Nove",
        "Paramount Network",
        "Rai 1",
        "Rai 2",
        "Rai 3",
        "Rai 4",
        "Rai 5",
        "Rai Gulp",
        "Rai Movie",
        "Rai News 24",
        "Rai Premium",
        "Rai Scuola",
        "Rai Sport",
        "Rai Storia",
        "Rai YoYo",
        "Real Time",
        "Rete 4",
        "Sky TG24",
        "TGCom24",
        "TopCrime",
        "Tv8",
        "Sky Uno",
        "Sky Arte",
        "Sky Atlantic",
        "Sky Serie",
        "Sky Documentaries",
        "Sky Nature",
        "Sky Investigation",
        "FOX",
        "Crime + INV",
        "Sky Sport Uno"
    ],
    recordingAudioChannels: [
        "Radio 105",
        "Radio 24",
        "Radio Capital",
        "Radio Deejay",
        "Radio Freccia",
        "Radio Italia smi",
        "Radio Zeta",
        "Radio Kiss Kiss Network",
        "RDS",
        "RMC",
        "Radio m2o",
        "Rai Isoradio",
        "Rai Radio 1",
        "Rai Radio 2",
        "Rai Radio 3",
        "RTL 102.5",
        "Virgin Radio",
        "R101"
    ]
    
}